### ISSUE TITLE
Test-Link

### ISSUE THREAD

**Issue by peppi02** [kadse/EM-Manager#1]
Ist das Spiel vielleicht irgendwo installiert, das man es testen kann ?
Freue mich auf kurze Info

**Comment by kadse** [comment]
Aktuell ist es nirgends installiert, aber prinzipiell ist ja alles im Repo um den WS auf einen eigenen Server aufzusetzen.

**Comment by peppi02** [comment]
Danke für die Info. Das bedeutet, dass es im Prinzip das gleiche ist wie das originale WS ? Keine Veränderungen ?

**Comment by kadse** [comment]
Doch der WS hier ist deutlich angepasst wurden, ich habe aber nicht mehr genau im Kopf was es alles war, dafür ist es zulange her.

**Comment by peppi02** [comment]
Ok, danke. Hättest Du vielleicht noch einen Tipp, woher man noch die Module bekommen kann, die es für den WS damals kostenlos gab ?

**Comment by kadse** [comment]
Nein, das kann ich dir nicht beantworten, wo es die noch gibt. Ich selber hab sie auch nicht mehr.

**Comment by peppi02** [comment]
Ok, danke für die Info.
